In [1]:
l = [23245, 27, 546, 215, -1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [3]:
import numpy as np

In [6]:
a = np.array(l)

In [7]:
a

array([23245,    27,   546,   215, -1234])

In [8]:
b = np.array([12, 455, 63.3, True, 'abc'])

In [10]:
l.pop()

-1234

In [11]:
a.mean()

4559.8000000000002

In [12]:
l[::2]

[23245, 546]

In [13]:
a

array([23245,    27,   546,   215, -1234])

In [14]:
a[2]

546

In [15]:
a[2:4]

array([546, 215])

In [16]:
b = a[2:4]

In [17]:
b[0]

546

In [18]:
b[:] = 111

In [19]:
b

array([111, 111])

In [20]:
a

array([23245,    27,   111,   111, -1234])

In [21]:
c = a.copy()

In [22]:
c

array([23245,    27,   111,   111, -1234])

In [23]:
c[0]

23245